grep -P chr1_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus1.sh
grep -P chr10_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus10.sh
grep -P chr11_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus11.sh
grep -P chr12_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus12.sh
grep -P chr13_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus13.sh
grep -P chr14_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus14.sh
grep -P chr15_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus15.sh
grep -P chr16_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus16.sh
grep -P chr17_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus17.sh
grep -P chr18_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus18.sh
grep -P chr19_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus19.sh
grep -P chr2_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus2.sh
grep -P chr20_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus20.sh
grep -P chr21_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus21.sh
grep -P chr22_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus22.sh
grep -P chr3_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus3.sh
grep -P chr4_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus4.sh
grep -P chr5_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus5.sh
grep -P chr6_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus6.sh
grep -P chr7_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus7.sh
grep -P chr8_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus8.sh
grep -P chr9_ getSNPEffectSizesRandCpGScriptPlus.sh > getSNPEffectSizesRandCpGScriptPlus9.sh
