python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.exon.cis.FDR5.all.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInExoneQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.exon.cis.FDR5.best.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestExoneQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.gene.cis.FDR5.all.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGeneeQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.gene.cis.FDR5.best.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestGeneeQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.repeat.cis.FDR5.all.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInRepeateQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.repeat.cis.FDR5.best.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestRepeateQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.trratio.cis.FDR5.all.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInTrRatioeQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GeuvadiseQTLData/YRI89.trratio.cis.FDR5.best.rs137.SNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestTrRatioeQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/dsQTLData/GSE31388_dsQtlSNPshg19.txt ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIndsQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/dsQTLData/GSE31388_dsQtlSNPsLonghg19.txt ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInLongdsQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/dsQTLData/GSE31388_eQtlSNPshg19.txt ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIndseQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/eQTLData/final_eqtl_listSNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIneQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/eQTLData/final_sqtl_listSNPLocations ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInsQTLs
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GWASData/SNAPResultsSNPCoordshg19.txt ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGWAS
python getSNPOverlapPlus.py ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPs /scr/MethylationQTLProject/GWASData/SNAPResults8SNPCoordshg19.txt ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGWAS8
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInExoneQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestExoneQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGeneeQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestGeneeQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInRepeateQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestRepeateQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInTrRatioeQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInBestTrRatioeQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIndsQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInLongdsQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIndseQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsIneQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInsQTLs
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGWAS
wc ../HiseqDataProcessed/mQTLDataNew/chrAll_CpG_fisherExact001pVal001_mQTLsSNPsInGWAS8
