zgrep -P 'chr1\t' /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr1_CHH_All_methylBatchFactors.gz
zgrep chr10 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr10_CHH_All_methylBatchFactors.gz
zgrep chr11 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr11_CHH_All_methylBatchFactors.gz
zgrep chr12 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr12_CHH_All_methylBatchFactors.gz
zgrep chr13 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr13_CHH_All_methylBatchFactors.gz
zgrep chr14 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr14_CHH_All_methylBatchFactors.gz
zgrep chr15 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr15_CHH_All_methylBatchFactors.gz
zgrep chr16 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr16_CHH_All_methylBatchFactors.gz
zgrep chr17 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr17_CHH_All_methylBatchFactors.gz
zgrep chr18 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr18_CHH_All_methylBatchFactors.gz
zgrep chr19 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr19_CHH_All_methylBatchFactors.gz
zgrep -P 'chr2\t' /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr2_CHH_All_methylBatchFactors.gz
zgrep chr20 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr20_CHH_All_methylBatchFactors.gz
zgrep chr21 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr21_CHH_All_methylBatchFactors.gz
zgrep chr22 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr22_CHH_All_methylBatchFactors.gz
zgrep chr3 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr3_CHH_All_methylBatchFactors.gz
zgrep chr4 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr4_CHH_All_methylBatchFactors.gz
zgrep chr5 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr5_CHH_All_methylBatchFactors.gz
zgrep chr6 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr6_CHH_All_methylBatchFactors.gz
zgrep chr7 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr7_CHH_All_methylBatchFactors.gz
zgrep chr8 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr8_CHH_All_methylBatchFactors.gz
zgrep chr9 /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chr9_CHH_All_methylBatchFactors.gz
zgrep chrX /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chrX_CHH_All_methylBatchFactors.gz
zgrep chrY /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chrY_CHH_All_methylBatchFactors.gz
zgrep chrM /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/CHH_All_methylBatchFactors.gz | sort -k3,3n -T /tmp | gzip > /science/irene/MethylationQTLProject/HiseqDataProcessed/HiseqDataMethylation/chrM_CHH_All_methylBatchFactors.gz
