zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescChd1a301218aStdPk.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescChd1a301218aIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeChd1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescChd7a301223a1Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeChd7.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescCtcfStdPk.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescCtcfsc5916V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescCtcfsc5916V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCtcf.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescEzh239875Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeEzh2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH2azStdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH2az.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k09me3StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k9me3.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k27acStdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k27ac.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k27me3StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k27me3.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k36me3StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k36me3.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k4me1StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k4me1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k4me2StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k4me2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k4me3StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k4me3.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k79me2StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k79me2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH3k9acStdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH3k9ac.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescH4k20me1StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeH4k20me1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescHdac2a300705aPk.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescHdac2sc6296V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescHdac2sc6296V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHdac2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescHdac6a301341aPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHdac6.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescJarid1aab26049StdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeJarid1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescJmjd2aa300861a1Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeJmjd2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescP300kat3bPk.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescP300V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescP300V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeP300.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescPhf8a301772aPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodePhf8.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescPlu1Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodePlu1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescRbbp5a300109aStdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeRbbp5.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescSap3039731Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSap.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescSirt6Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSirt6.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBroadHistoneH1hescSuz12051317Pk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSuz12.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescAtf2sc81188V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescAtf2sc81188V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeAtf2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescAtf3V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescAtf3V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeAtf3.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescBcl11aPcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescBcl11aV0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBcl11a.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescCreb1sc240V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescCreb1sc240V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCreb1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescE2f6V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescE2f6V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeE2f6.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescEgr1V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescEgr1V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeEgr1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescFosl1sc183V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescFosl1sc183V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeFosl1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescGabpPcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescGabpPcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeGabp.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescJundV0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescJundV0416102PkRep2.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescJundIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeJund.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescMaxV0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescMaxV0422111PkRep2.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescMaxUcdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeMax.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescNanogsc33759V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescNanogsc33759V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodNanog.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescNrsfV0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescNrsfV0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeNrsf.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPol24h8V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPol24h8V0416102PkRep2.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPol2V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPol2V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodePol2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPou5f1sc9081V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescPou5f1sc9081V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodePou5f1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescRad21V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescRad21V0416102PkRep2.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescRad21IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeRad21.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescRxraV0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescRxraV0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeRxra.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSin3ak20Pcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSin3ak20Pcr1xPkRep2.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescSin3anb6001263IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSin3a.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSix5Pcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSix5Pcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSix5.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp1Pcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp1Pcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSp1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp2V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp2V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSp2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp4v20V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSp4v20V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSp4.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSrfPcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescSrfPcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSrf.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTaf1V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTaf1V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeTaf1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTaf7sc101167V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTaf7sc101167V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeTaf7.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTcf12Pcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTcf12Pcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeTcf12.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTead4sc101184V0422111PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescTead4sc101184V0422111PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeTead4.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescUsf1Pcr1xPkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescUsf1Pcr1xPkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeUsf1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescYy1sc281V0416102PkRep1.sorted.gz /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeHaibTfbsH1hescYy1sc281V0416102PkRep2.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeYy1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescBach1sc14700IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBach.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescBrca1IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeBrca1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescCebpbIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCebpb.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescChd2IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeChd2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescCjunIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCjun.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescCmycIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCmyc.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescCtbp2UcdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeCtbp2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescGtf2f1IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeGtf2f1.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescMafkIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeMafk.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescMxi1IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeMxi.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescNrf1IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeNrf.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescRfx5200401194IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeRfx5.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescSuz12UcdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSuz12.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescTbpIggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeTbp.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescUsf2IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeUsf2.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescZnf143IggrabPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeZnf143.all.sorted.gz
zcat /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeSydhTfbsH1hescZnf274m01UcdPk.sorted.gz | cut -f1,2,3 | sort -u -k1,1 -k2,2n -k3,3n | gzip > /science/irene/MethylationQTLProject/ENCODEH1hescData/wgEncodeZnf274.all.sorted.gz
